import 'package:flutter/widgets.dart';
import 'content_translations.dart';
import 'ui_translation_additions.dart';

class AppLocaleScope extends InheritedWidget {
  const AppLocaleScope({
    super.key,
    required this.languageCode,
    required super.child,
  });

  final String languageCode;

  static AppLocaleScope of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<AppLocaleScope>() ??
        const AppLocaleScope(languageCode: 'en', child: SizedBox.shrink());
  }

  String translate(String value) {
    return translations[languageCode]?[value] ??
        additionalUiTranslations[languageCode]?[value] ??
        translateContent(languageCode, value);
  }

  @override
  bool updateShouldNotify(AppLocaleScope oldWidget) =>
      oldWidget.languageCode != languageCode;

  static const Map<String, Map<String, String>> translations = {
    'ta': {
      'English': 'ஆங்கிலம்',
      'Tamil': 'தமிழ்',
      'Telugu': 'தெலுங்கு',
      'Home': 'முகப்பு',
      'Search': 'தேடல்',
      'Tickets': 'டிக்கெட்டுகள்',
      'Profile': 'சுயவிவரம்',
      'Settings': 'அமைப்புகள்',
      'Language': 'மொழி',
      'Language Preference': 'மொழி விருப்பம்',
      'Preferences': 'விருப்பங்கள்',
      'Appearance': 'தோற்றம்',
      'Dark Mode': 'டார்க் மோடு',
      'Notifications': 'அறிவிப்புகள்',
      'Booking updates, reminders and offers':
          'முன்பதிவு புதுப்பிப்புகள், நினைவூட்டல்கள் மற்றும் சலுகைகள்',
      'App Version': 'செயலி பதிப்பு',
      'Movies': 'திரைப்படங்கள்',
      'Events': 'நிகழ்வுகள்',
      'Metro': 'மெட்ரோ',
      'Metro Tickets': 'மெட்ரோ டிக்கெட்டுகள்',
      'Offers': 'சலுகைகள்',
      'See All': 'அனைத்தையும் காண்க',
      'View All': 'அனைத்தையும் பார்க்கவும்',
      'Now Showing': 'தற்போது திரையிடப்படுகிறது',
      'Events Near You': 'உங்கள் அருகிலுள்ள நிகழ்வுகள்',
      'Popular Theatres': 'பிரபலமான திரையரங்குகள்',
      'Upcoming Movies': 'வரவிருக்கும் திரைப்படங்கள்',
      'Trending Events': 'டிரெண்டிங் நிகழ்வுகள்',
      'Metro Routes': 'மெட்ரோ வழித்தடங்கள்',
      'Hot Offers': 'சிறப்பு சலுகைகள்',
      'Discover experiences that stay with you':
          'நினைவில் நிற்கும் அனுபவங்களை கண்டறியுங்கள்',
      'Book Tickets': 'டிக்கெட்டுகளை முன்பதிவு செய்க',
      'Select Seats': 'இருக்கைகளைத் தேர்ந்தெடுக்கவும்',
      'Proceed to Checkout': 'செக் அவுட்டிற்கு செல்லவும்',
      'Checkout': 'செக் அவுட்',
      'Apply Coupon': 'கூப்பனைப் பயன்படுத்தவும்',
      'Enter promo code': 'சலுகைக் குறியீட்டை உள்ளிடவும்',
      'Apply': 'பயன்படுத்து',
      'Payment Method': 'கட்டண முறை',
      'Cancellation Policy': 'ரத்து விதிமுறை',
      'Complete Demo Booking': 'டெமோ முன்பதிவை முடிக்கவும்',
      'Available': 'கிடைக்கிறது',
      'Selected': 'தேர்ந்தெடுக்கப்பட்டது',
      'Booked': 'முன்பதிவு செய்யப்பட்டது',
      'Best Price Guaranteed': 'சிறந்த விலை உத்தரவாதம்',
      'Ticket Details': 'டிக்கெட் விவரங்கள்',
      'Upcoming': 'வரவிருப்பவை',
      'Completed': 'நிறைவடைந்தவை',
      'Cancelled': 'ரத்து செய்யப்பட்டவை',
      'Expired': 'காலாவதியானவை',
      'Share': 'பகிர்',
      'Go to Home': 'முகப்புக்குச் செல்லவும்',
      'From': 'இருந்து',
      'To': 'வரை',
      'Check Route': 'வழியைச் சரிபார்க்கவும்',
      'All lines operational': 'அனைத்து வழித்தடங்களும் இயங்குகின்றன',
      'Live Network Map': 'நேரடி நெட்வொர்க் வரைபடம்',
      'Recently Travelled': 'சமீபத்திய பயணங்கள்',
      'Favourite Routes': 'பிடித்த வழித்தடங்கள்',
      'Save routes you travel often for quick access.':
          'அடிக்கடி பயணிக்கும் வழிகளை விரைவான அணுகலுக்காக சேமிக்கவும்.',
      'Select station': 'நிலையத்தைத் தேர்ந்தெடுக்கவும்',
      'Search stations': 'நிலையங்களைத் தேடவும்',
      'Popular Stations': 'பிரபலமான நிலையங்கள்',
      'No stations found': 'நிலையங்கள் எதுவும் கிடைக்கவில்லை',
      'Route Details': 'வழி விவரங்கள்',
      'Select both stations to view route':
          'வழியைப் பார்க்க இரு நிலையங்களையும் தேர்ந்தெடுக்கவும்',
      'View on live map': 'நேரடி வரைபடத்தில் பார்க்கவும்',
      'Number of Passengers': 'பயணிகளின் எண்ணிக்கை',
      'One-time use only': 'ஒருமுறை மட்டும் பயன்படுத்தவும்',
      'Tap a station to select it': 'நிலையத்தைத் தேர்ந்தெடுக்க தட்டவும்',
      'Set as From': 'புறப்படும் நிலையமாக அமைக்கவும்',
      'Set as To': 'சேரும் நிலையமாக அமைக்கவும்',
      'About': 'பற்றி',
      'Cast': 'நடிகர்கள்',
      'Synopsis': 'கதைச்சுருக்கம்',
      'Read More': 'மேலும் படிக்கவும்',
      'Read Less': 'குறைவாகப் படிக்கவும்',
      'User Reviews': 'பயனர் விமர்சனங்கள்',
      'Available Theatres': 'கிடைக்கும் திரையரங்குகள்',
      'You May Also Like': 'உங்களுக்கு பிடிக்கக்கூடியவை',
      'Select Show': 'காட்சியைத் தேர்ந்தெடுக்கவும்',
      'No movies found': 'திரைப்படங்கள் எதுவும் கிடைக்கவில்லை',
      'No events found': 'நிகழ்வுகள் எதுவும் கிடைக்கவில்லை',
      'No events in this category yet': 'இந்த வகையில் இன்னும் நிகழ்வுகள் இல்லை',
      'No events near you yet': 'உங்கள் அருகில் இன்னும் நிகழ்வுகள் இல்லை',
      'No shows on this date': 'இந்த தேதியில் காட்சிகள் இல்லை',
      'Try selecting another date': 'வேறு தேதியைத் தேர்ந்தெடுக்கவும்',
      'Coming': 'வெளியாகிறது',
      'Music': 'இசை',
      'Comedy': 'நகைச்சுவை',
      'Sports': 'விளையாட்டு',
      'Workshops': 'பயிற்சிப் பட்டறைகள்',
      'Art & Culture': 'கலை மற்றும் கலாசாரம்',
      'Popular': 'பிரபலமானது',
      'Recommended For You': 'உங்களுக்கான பரிந்துரைகள்',
      'Upcoming Events': 'வரவிருக்கும் நிகழ்வுகள்',
      'Get Started': 'தொடங்குங்கள்',
      'Next': 'அடுத்து',
      'Skip': 'தவிர்க்கவும்',
      'Continue': 'தொடரவும்',
      'Enter your mobile number': 'உங்கள் மொபைல் எண்ணை உள்ளிடவும்',
      'Send OTP': 'OTP அனுப்பவும்',
      'Verify your number': 'உங்கள் எண்ணைச் சரிபார்க்கவும்',
      'Verify & Continue': 'சரிபார்த்து தொடரவும்',
      'Resend OTP': 'OTP-ஐ மீண்டும் அனுப்பவும்',
      'Trailer playback is not available in this demo':
          'இந்த டெமோவில் டிரெய்லர் இயக்கம் கிடைக்கவில்லை',
      'Live map not set up yet': 'நேரடி வரைபடம் இன்னும் அமைக்கப்படவில்லை',
      'Search stations instead': 'அதற்கு பதிலாக நிலையங்களைத் தேடவும்',
      'Kalki 2898 AD': 'கல்கி 2898 AD',
      'Pushpa 2': 'புஷ்பா 2',
      'Leo': 'லியோ',
      'Animal': 'அனிமல்',
      'Anirudh Live in Concert': 'அனிருத் நேரலை இசை நிகழ்ச்சி',
      'TechSpark Summit': 'டெக்ஸ்பார்க் உச்சி மாநாடு',
      'Chennai Marathon': 'சென்னை மாரத்தான்',
      'Laugh Riot': 'சிரிப்பு கலாட்டா',
      'Flat ₹100 Off': '₹100 தள்ளுபடி',
      '20% Off on Events': 'நிகழ்வுகளுக்கு 20% தள்ளுபடி',
      'Metro Combo Saver': 'மெட்ரோ காம்போ சேவர்',
      'Weekend Movie Bonanza': 'வார இறுதி திரைப்பட சலுகை',
    },
    'te': {
      'English': 'ఆంగ్లం',
      'Tamil': 'తమిళం',
      'Telugu': 'తెలుగు',
      'Home': 'హోమ్',
      'Search': 'శోధన',
      'Tickets': 'టికెట్లు',
      'Profile': 'ప్రొఫైల్',
      'Settings': 'సెట్టింగ్‌లు',
      'Language': 'భాష',
      'Language Preference': 'భాష ఎంపిక',
      'Preferences': 'ప్రాధాన్యతలు',
      'Appearance': 'రూపం',
      'Dark Mode': 'డార్క్ మోడ్',
      'Notifications': 'నోటిఫికేషన్లు',
      'Booking updates, reminders and offers':
          'బుకింగ్ అప్‌డేట్లు, రిమైండర్లు మరియు ఆఫర్లు',
      'App Version': 'యాప్ వెర్షన్',
      'Movies': 'సినిమాలు',
      'Events': 'ఈవెంట్లు',
      'Metro': 'మెట్రో',
      'Metro Tickets': 'మెట్రో టికెట్లు',
      'Offers': 'ఆఫర్లు',
      'See All': 'అన్నీ చూడండి',
      'View All': 'అన్నీ వీక్షించండి',
      'Now Showing': 'ప్రస్తుతం ప్రదర్శనలో',
      'Events Near You': 'మీ సమీపంలోని ఈవెంట్లు',
      'Popular Theatres': 'ప్రసిద్ధ థియేటర్లు',
      'Upcoming Movies': 'రాబోయే సినిమాలు',
      'Trending Events': 'ట్రెండింగ్ ఈవెంట్లు',
      'Metro Routes': 'మెట్రో మార్గాలు',
      'Hot Offers': 'ప్రత్యేక ఆఫర్లు',
      'Discover experiences that stay with you':
          'మీతో నిలిచిపోయే అనుభవాలను కనుగొనండి',
      'Book Tickets': 'టికెట్లు బుక్ చేయండి',
      'Select Seats': 'సీట్లను ఎంచుకోండి',
      'Proceed to Checkout': 'చెక్‌అవుట్‌కు వెళ్లండి',
      'Checkout': 'చెక్‌అవుట్',
      'Apply Coupon': 'కూపన్ వర్తింపజేయండి',
      'Enter promo code': 'ప్రోమో కోడ్ నమోదు చేయండి',
      'Apply': 'వర్తింపజేయి',
      'Payment Method': 'చెల్లింపు విధానం',
      'Cancellation Policy': 'రద్దు విధానం',
      'Complete Demo Booking': 'డెమో బుకింగ్ పూర్తి చేయండి',
      'Available': 'అందుబాటులో ఉంది',
      'Selected': 'ఎంచుకున్నది',
      'Booked': 'బుక్ చేయబడింది',
      'Best Price Guaranteed': 'ఉత్తమ ధరకు హామీ',
      'Ticket Details': 'టికెట్ వివరాలు',
      'Upcoming': 'రాబోయేవి',
      'Completed': 'పూర్తయినవి',
      'Cancelled': 'రద్దైనవి',
      'Expired': 'గడువు ముగిసినవి',
      'Share': 'షేర్ చేయండి',
      'Go to Home': 'హోమ్‌కు వెళ్లండి',
      'From': 'నుండి',
      'To': 'వరకు',
      'Check Route': 'మార్గాన్ని తనిఖీ చేయండి',
      'All lines operational': 'అన్ని మార్గాలు పనిచేస్తున్నాయి',
      'Live Network Map': 'లైవ్ నెట్‌వర్క్ మ్యాప్',
      'Recently Travelled': 'ఇటీవల ప్రయాణించినవి',
      'Favourite Routes': 'ఇష్టమైన మార్గాలు',
      'Save routes you travel often for quick access.':
          'తరచుగా ప్రయాణించే మార్గాలను త్వరిత ప్రాప్యత కోసం సేవ్ చేయండి.',
      'Select station': 'స్టేషన్ ఎంచుకోండి',
      'Search stations': 'స్టేషన్లను శోధించండి',
      'Popular Stations': 'ప్రసిద్ధ స్టేషన్లు',
      'No stations found': 'స్టేషన్లు ఏవీ కనబడలేదు',
      'Route Details': 'మార్గ వివరాలు',
      'Select both stations to view route':
          'మార్గాన్ని చూడటానికి రెండు స్టేషన్లను ఎంచుకోండి',
      'View on live map': 'లైవ్ మ్యాప్‌లో చూడండి',
      'Number of Passengers': 'ప్రయాణికుల సంఖ్య',
      'One-time use only': 'ఒక్కసారి మాత్రమే ఉపయోగించాలి',
      'Tap a station to select it': 'ఎంచుకోవడానికి స్టేషన్‌పై ట్యాప్ చేయండి',
      'Set as From': 'ప్రారంభ స్టేషన్‌గా సెట్ చేయండి',
      'Set as To': 'గమ్య స్టేషన్‌గా సెట్ చేయండి',
      'About': 'గురించి',
      'Cast': 'నటీనటులు',
      'Synopsis': 'కథా సారాంశం',
      'Read More': 'మరింత చదవండి',
      'Read Less': 'తక్కువగా చదవండి',
      'User Reviews': 'వినియోగదారుల సమీక్షలు',
      'Available Theatres': 'అందుబాటులో ఉన్న థియేటర్లు',
      'You May Also Like': 'మీకు నచ్చవచ్చినవి',
      'Select Show': 'షో ఎంచుకోండి',
      'No movies found': 'సినిమాలు ఏవీ కనబడలేదు',
      'No events found': 'ఈవెంట్లు ఏవీ కనబడలేదు',
      'No events in this category yet': 'ఈ విభాగంలో ఇంకా ఈవెంట్లు లేవు',
      'No events near you yet': 'మీ సమీపంలో ఇంకా ఈవెంట్లు లేవు',
      'No shows on this date': 'ఈ తేదీన షోలు లేవు',
      'Try selecting another date': 'మరొక తేదీని ఎంచుకోండి',
      'Coming': 'విడుదల',
      'Music': 'సంగీతం',
      'Comedy': 'కామెడీ',
      'Sports': 'క్రీడలు',
      'Workshops': 'వర్క్‌షాప్‌లు',
      'Art & Culture': 'కళ మరియు సంస్కృతి',
      'Popular': 'ప్రసిద్ధం',
      'Recommended For You': 'మీ కోసం సిఫార్సులు',
      'Upcoming Events': 'రాబోయే ఈవెంట్లు',
      'Get Started': 'ప్రారంభించండి',
      'Next': 'తదుపరి',
      'Skip': 'దాటవేయి',
      'Continue': 'కొనసాగించండి',
      'Enter your mobile number': 'మీ మొబైల్ నంబర్ నమోదు చేయండి',
      'Send OTP': 'OTP పంపండి',
      'Verify your number': 'మీ నంబర్‌ను ధృవీకరించండి',
      'Verify & Continue': 'ధృవీకరించి కొనసాగించండి',
      'Resend OTP': 'OTP మళ్లీ పంపండి',
      'Trailer playback is not available in this demo':
          'ఈ డెమోలో ట్రైలర్ ప్లేబ్యాక్ అందుబాటులో లేదు',
      'Live map not set up yet': 'లైవ్ మ్యాప్ ఇంకా సెటప్ కాలేదు',
      'Search stations instead': 'బదులుగా స్టేషన్లను శోధించండి',
      'Kalki 2898 AD': 'కల్కి 2898 AD',
      'Pushpa 2': 'పుష్ప 2',
      'Leo': 'లియో',
      'Animal': 'యానిమల్',
      'Anirudh Live in Concert': 'అనిరుధ్ లైవ్ కచేరీ',
      'TechSpark Summit': 'టెక్‌స్పార్క్ సమ్మిట్',
      'Chennai Marathon': 'చెన్నై మారథాన్',
      'Laugh Riot': 'లాఫ్ రయట్',
      'Flat ₹100 Off': '₹100 తగ్గింపు',
      '20% Off on Events': 'ఈవెంట్లపై 20% తగ్గింపు',
      'Metro Combo Saver': 'మెట్రో కాంబో సేవర్',
      'Weekend Movie Bonanza': 'వీకెండ్ మూవీ బొనాంజా',
    },
  };
}

class AppLocale {
  AppLocale._();

  static String languageCode = 'en';

  static void setLanguage(String code) {
    languageCode = code;
  }

  static String tr(String value) {
    return AppLocaleScope.translations[languageCode]?[value] ??
        additionalUiTranslations[languageCode]?[value] ??
        translateContent(languageCode, value);
  }
}

extension AppLocalizationContext on BuildContext {
  String tr(String value) => AppLocaleScope.of(this).translate(value);
}
